extends Node
class_name ArmorCatalog
## Central catalog of wearable armor (helmets / chests / pants).
##
## Each entry is a plain item dictionary in the SAME format the inventory/equip
## system already uses (see player.gd STARTING_STAFF and chest.gd LOOT_SETS):
##   name, rarity, tier, edition, slot, color, + stat modifiers.
##
## Stat modifiers (any may be omitted; omitted = 0):
##   move_mod      float  +/- walk speed (m/s)        -> mobility
##   jump_mod      float  +/- jump take-off velocity  -> mobility
##   health_bonus  int    +/- max HP                  -> health
##   stamina_bonus float  +/- max stamina             -> stamina
##   regen_bonus   float  +/- stamina regen / sec     -> stamina
##
## The "model" field selects a PROCEDURAL SHAPE built by humanoid.gd
## (apply_equipment), so pieces look genuinely different — not just recolored.
## To add a new look: add an entry here with a new "model" id, then add a branch
## for that id in humanoid.gd (_build_helmet / _build_chest / _build_legs).
##
## Design intent (so trade-offs feel meaningful, never strictly-better):
##   heavy metal  -> big +HP, but -move / -jump / -stamina
##   cloth/robe   -> +stamina / +regen / a little +move, little or negative HP
##   leather      -> modest all-round, small bonuses
##   exotic/magic -> one strong stat with a matching drawback

# accent colors reused across pieces
const GOLD := Color(0.85, 0.72, 0.28)
const BONE := Color(0.90, 0.87, 0.78)
const STEEL := Color(0.62, 0.64, 0.70)
const IRON := Color(0.50, 0.52, 0.58)

const HELMETS := [
	{"name": "Cloth Hood", "rarity": "Common", "tier": 1, "edition": 88, "slot": "helmet",
		"model": "hood", "color": Color(0.40, 0.30, 0.52),
		"move_mod": 0.2, "jump_mod": 0.1, "stamina_bonus": 10.0},
	{"name": "Leather Cap", "rarity": "Common", "tier": 1, "edition": 64, "slot": "helmet",
		"model": "cap", "color": Color(0.42, 0.28, 0.16),
		"health_bonus": 8, "stamina_bonus": 4.0},
	{"name": "Iron Helm", "rarity": "Uncommon", "tier": 2, "edition": 22, "slot": "helmet",
		"model": "great_helm", "color": IRON,
		"health_bonus": 25, "move_mod": -0.3, "jump_mod": -0.4},
	{"name": "Knight's Barbute", "rarity": "Uncommon", "tier": 2, "edition": 17, "slot": "helmet",
		"model": "barbute", "color": STEEL,
		"health_bonus": 20, "move_mod": -0.2},
	{"name": "Wizard's Hat", "rarity": "Rare", "tier": 3, "edition": 9, "slot": "helmet",
		"model": "wizard_hat", "color": Color(0.24, 0.18, 0.42),
		"stamina_bonus": 25.0, "regen_bonus": 6.0, "move_mod": 0.1, "health_bonus": -5},
	{"name": "Arcane Circlet", "rarity": "Rare", "tier": 3, "edition": 7, "slot": "helmet",
		"model": "circlet", "color": GOLD,
		"stamina_bonus": 20.0, "regen_bonus": 8.0, "move_mod": 0.15},
	{"name": "Horned Warhelm", "rarity": "Rare", "tier": 3, "edition": 5, "slot": "helmet",
		"model": "horned", "color": Color(0.34, 0.30, 0.34),
		"health_bonus": 30, "move_mod": -0.35, "stamina_bonus": -10.0},
	{"name": "Bone Skull-Mask", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "helmet",
		"model": "bone", "color": BONE,
		"health_bonus": 10, "move_mod": 0.2, "jump_mod": 0.2, "regen_bonus": -3.0},
	{"name": "Gilded Crown", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "helmet",
		"model": "crown", "color": GOLD,
		"health_bonus": 15, "stamina_bonus": 15.0, "regen_bonus": 4.0},
	{"name": "Winged Helm", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "helmet",
		"model": "winged", "color": Color(0.78, 0.80, 0.86),
		"move_mod": 0.3, "jump_mod": 0.5, "health_bonus": 5},
	{"name": "Jester's Cap", "rarity": "Uncommon", "tier": 2, "edition": 30, "slot": "helmet",
		"model": "jester", "color": Color(0.55, 0.20, 0.45),
		"stamina_bonus": 15.0, "regen_bonus": 5.0, "move_mod": 0.2, "health_bonus": -5},
	{"name": "Viking Helm", "rarity": "Uncommon", "tier": 2, "edition": 21, "slot": "helmet",
		"model": "viking", "color": Color(0.58, 0.60, 0.66),
		"health_bonus": 24, "move_mod": -0.25},
	{"name": "Iron Kabuto", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "helmet",
		"model": "kabuto", "color": Color(0.36, 0.14, 0.16),
		"health_bonus": 20, "stamina_bonus": 8.0},
	{"name": "Plague Mask", "rarity": "Rare", "tier": 3, "edition": 6, "slot": "helmet",
		"model": "plague", "color": Color(0.20, 0.20, 0.24),
		"regen_bonus": 10.0, "stamina_bonus": 12.0, "health_bonus": -8},
	{"name": "Spartan Helm", "rarity": "Rare", "tier": 3, "edition": 5, "slot": "helmet",
		"model": "spartan", "color": Color(0.70, 0.52, 0.26),
		"health_bonus": 28, "move_mod": -0.3, "jump_mod": -0.3},
	{"name": "Antler Crown", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "helmet",
		"model": "antlers", "color": Color(0.34, 0.22, 0.14),
		"move_mod": 0.25, "jump_mod": 0.3, "stamina_bonus": 10.0},
	{"name": "Jeweled Tiara", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "helmet",
		"model": "tiara", "color": GOLD,
		"stamina_bonus": 18.0, "regen_bonus": 6.0, "move_mod": 0.1},
	{"name": "Demon Helm", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "helmet",
		"model": "demon", "color": Color(0.30, 0.10, 0.12),
		"health_bonus": 35, "move_mod": -0.3, "stamina_bonus": -5.0},
	{"name": "Flame Crown", "rarity": "Rare", "tier": 3, "edition": 7, "slot": "helmet",
		"model": "flame_crown", "color": Color(0.55, 0.18, 0.10),
		"stamina_bonus": 15.0, "regen_bonus": 6.0, "move_mod": 0.1, "health_bonus": -3},
	{"name": "Frost Crown", "rarity": "Rare", "tier": 3, "edition": 6, "slot": "helmet",
		"model": "ice_crown", "color": Color(0.55, 0.72, 0.85),
		"health_bonus": 18, "stamina_bonus": 10.0},
	{"name": "Storm Helm", "rarity": "Rare", "tier": 3, "edition": 5, "slot": "helmet",
		"model": "storm_helm", "color": Color(0.42, 0.48, 0.60),
		"move_mod": 0.25, "stamina_bonus": 12.0, "jump_mod": 0.2},
	{"name": "Halo Crown", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "helmet",
		"model": "halo", "color": Color(0.95, 0.92, 0.85),
		"health_bonus": 20, "regen_bonus": 10.0, "stamina_bonus": 10.0},
	{"name": "Shadow Hood", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "helmet",
		"model": "shadow_hood", "color": Color(0.16, 0.12, 0.22),
		"move_mod": 0.3, "stamina_bonus": 15.0, "health_bonus": -10},
	{"name": "Druid Hood", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "helmet",
		"model": "druid_hood", "color": Color(0.24, 0.40, 0.22),
		"stamina_bonus": 14.0, "regen_bonus": 6.0, "health_bonus": 8},
	{"name": "Crystal Helm", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "helmet",
		"model": "crystal_helm", "color": Color(0.45, 0.78, 0.85),
		"health_bonus": 22, "stamina_bonus": 12.0},
	{"name": "Pharaoh's Nemes", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "helmet",
		"model": "pharaoh", "color": Color(0.30, 0.40, 0.62),
		"health_bonus": 15, "stamina_bonus": 15.0, "regen_bonus": 5.0},
	{"name": "Mushroom Cap", "rarity": "Rare", "tier": 3, "edition": 9, "slot": "helmet",
		"model": "mushroom", "color": Color(0.66, 0.22, 0.20),
		"regen_bonus": 12.0, "stamina_bonus": 10.0, "health_bonus": 5, "move_mod": -0.1},
	{"name": "Ram-Horn Helm", "rarity": "Rare", "tier": 3, "edition": 5, "slot": "helmet",
		"model": "war_horns", "color": Color(0.40, 0.42, 0.46),
		"health_bonus": 30, "move_mod": -0.3},
	{"name": "Silk Turban", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "helmet",
		"model": "turban", "color": Color(0.32, 0.24, 0.50),
		"stamina_bonus": 18.0, "regen_bonus": 6.0, "move_mod": 0.15},
	{"name": "Centurion Helm", "rarity": "Uncommon", "tier": 2, "edition": 19, "slot": "helmet",
		"model": "centurion", "color": Color(0.58, 0.60, 0.66),
		"health_bonus": 26, "move_mod": -0.2},
	{"name": "Topknot Helm", "rarity": "Uncommon", "tier": 2, "edition": 16, "slot": "helmet",
		"model": "topknot", "color": Color(0.30, 0.20, 0.14),
		"health_bonus": 12, "stamina_bonus": 10.0, "move_mod": 0.1},
	{"name": "Wolf Pelt Hood", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "helmet",
		"model": "wolf_pelt", "color": Color(0.46, 0.42, 0.38),
		"move_mod": 0.3, "stamina_bonus": 12.0, "jump_mod": 0.2, "health_bonus": 5},
	{"name": "Skull Crown", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "helmet",
		"model": "skull_crown", "color": GOLD,
		"health_bonus": 20, "stamina_bonus": 10.0, "regen_bonus": -2.0},
	{"name": "Laurel Wreath", "rarity": "Rare", "tier": 3, "edition": 7, "slot": "helmet",
		"model": "laurel", "color": Color(0.34, 0.55, 0.26),
		"stamina_bonus": 16.0, "regen_bonus": 8.0, "move_mod": 0.2, "health_bonus": -3},
	{"name": "Brass Diving Helm", "rarity": "Rare", "tier": 3, "edition": 5, "slot": "helmet",
		"model": "diving_helm", "color": Color(0.66, 0.54, 0.28),
		"health_bonus": 30, "move_mod": -0.35, "stamina_bonus": -5.0},
	{"name": "Cyclops Visor", "rarity": "Rare", "tier": 3, "edition": 6, "slot": "helmet",
		"model": "cyclops", "color": Color(0.34, 0.36, 0.42),
		"health_bonus": 24, "move_mod": -0.2},
]

const CHESTS := [
	{"name": "Cloth Robe", "rarity": "Common", "tier": 1, "edition": 90, "slot": "chest",
		"model": "robe", "color": Color(0.36, 0.34, 0.55),
		"stamina_bonus": 20.0, "regen_bonus": 5.0, "move_mod": 0.1},
	{"name": "Leather Vest", "rarity": "Common", "tier": 1, "edition": 71, "slot": "chest",
		"model": "leather", "color": Color(0.45, 0.30, 0.18),
		"health_bonus": 15},
	{"name": "Iron Cuirass", "rarity": "Uncommon", "tier": 2, "edition": 28, "slot": "chest",
		"model": "plate", "color": IRON,
		"health_bonus": 40, "move_mod": -0.5, "jump_mod": -0.6, "stamina_bonus": -10.0},
	{"name": "Scale Mail", "rarity": "Uncommon", "tier": 2, "edition": 19, "slot": "chest",
		"model": "scale", "color": Color(0.46, 0.50, 0.46),
		"health_bonus": 28, "move_mod": -0.3},
	{"name": "Studded Brigandine", "rarity": "Uncommon", "tier": 2, "edition": 14, "slot": "chest",
		"model": "brigandine", "color": Color(0.36, 0.24, 0.16),
		"health_bonus": 22, "stamina_bonus": 5.0},
	{"name": "Ranger's Cloak", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "chest",
		"model": "cloak", "color": Color(0.22, 0.40, 0.26),
		"move_mod": 0.4, "jump_mod": 0.3, "stamina_bonus": 15.0, "health_bonus": 5},
	{"name": "Bonecage Harness", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "chest",
		"model": "bone", "color": BONE,
		"health_bonus": 18, "move_mod": 0.2, "regen_bonus": -3.0},
	{"name": "Archmage Robe", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "chest",
		"model": "ornate_robe", "color": Color(0.30, 0.16, 0.46),
		"stamina_bonus": 35.0, "regen_bonus": 10.0, "move_mod": 0.2, "health_bonus": -10},
	{"name": "Steel Cuirass", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "chest",
		"model": "ornate_plate", "color": STEEL,
		"health_bonus": 55, "move_mod": -0.6, "jump_mod": -0.8},
	{"name": "Fur Mantle", "rarity": "Uncommon", "tier": 2, "edition": 26, "slot": "chest",
		"model": "fur", "color": Color(0.40, 0.28, 0.18),
		"health_bonus": 20, "stamina_bonus": 6.0, "move_mod": -0.1},
	{"name": "Chainmail Hauberk", "rarity": "Uncommon", "tier": 2, "edition": 18, "slot": "chest",
		"model": "chainmail", "color": Color(0.55, 0.57, 0.62),
		"health_bonus": 30, "move_mod": -0.25},
	{"name": "Monk's Robe", "rarity": "Rare", "tier": 3, "edition": 9, "slot": "chest",
		"model": "monk", "color": Color(0.55, 0.42, 0.26),
		"stamina_bonus": 22.0, "regen_bonus": 8.0, "move_mod": 0.2, "health_bonus": -5},
	{"name": "Dragonscale Cuirass", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "chest",
		"model": "dragon", "color": Color(0.24, 0.42, 0.28),
		"health_bonus": 45, "move_mod": -0.3, "jump_mod": -0.4},
	{"name": "Royal Cuirass", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "chest",
		"model": "royal", "color": Color(0.22, 0.32, 0.58),
		"health_bonus": 40, "stamina_bonus": 10.0, "move_mod": -0.4},
	{"name": "Spellweave Robe", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "chest",
		"model": "spellweave", "color": Color(0.20, 0.28, 0.52),
		"stamina_bonus": 30.0, "regen_bonus": 12.0, "move_mod": 0.15, "health_bonus": -8},
	{"name": "Flame Plate", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "chest",
		"model": "flame_plate", "color": Color(0.45, 0.16, 0.10),
		"health_bonus": 35, "stamina_bonus": 8.0, "move_mod": -0.3},
	{"name": "Frost Plate", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "chest",
		"model": "ice_plate", "color": Color(0.50, 0.66, 0.78),
		"health_bonus": 38, "move_mod": -0.3, "jump_mod": -0.3},
	{"name": "Storm Robe", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "chest",
		"model": "storm_robe", "color": Color(0.24, 0.30, 0.50),
		"stamina_bonus": 25.0, "regen_bonus": 8.0, "move_mod": 0.25, "health_bonus": -6},
	{"name": "Radiant Plate", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "chest",
		"model": "holy_plate", "color": Color(0.92, 0.90, 0.80),
		"health_bonus": 45, "regen_bonus": 10.0, "move_mod": -0.3},
	{"name": "Shadow Robe", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "chest",
		"model": "shadow_robe", "color": Color(0.14, 0.10, 0.18),
		"move_mod": 0.4, "stamina_bonus": 18.0, "jump_mod": 0.3, "health_bonus": -12},
	{"name": "Barkmail", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "chest",
		"model": "druid_chest", "color": Color(0.36, 0.26, 0.16),
		"health_bonus": 30, "stamina_bonus": 10.0, "move_mod": -0.15},
	{"name": "Crystal Plate", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "chest",
		"model": "crystal_chest", "color": Color(0.40, 0.74, 0.82),
		"health_bonus": 40, "stamina_bonus": 12.0, "move_mod": -0.35},
	{"name": "Knight's Tabard", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "chest",
		"model": "tabard", "color": Color(0.58, 0.60, 0.66),
		"health_bonus": 38, "stamina_bonus": 6.0, "move_mod": -0.3},
	{"name": "Gladiator Harness", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "chest",
		"model": "gladiator", "color": Color(0.45, 0.32, 0.20),
		"health_bonus": 18, "move_mod": 0.2, "stamina_bonus": 10.0},
	{"name": "Samurai Do", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "chest",
		"model": "samurai_do", "color": Color(0.45, 0.16, 0.16),
		"health_bonus": 34, "move_mod": -0.25},
	{"name": "Ranger Trenchcoat", "rarity": "Rare", "tier": 3, "edition": 7, "slot": "chest",
		"model": "trenchcoat", "color": Color(0.30, 0.24, 0.18),
		"move_mod": 0.3, "stamina_bonus": 15.0, "health_bonus": 8},
	{"name": "Feathered Mantle", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "chest",
		"model": "feathered_cloak", "color": Color(0.88, 0.88, 0.92),
		"move_mod": 0.35, "jump_mod": 0.4, "stamina_bonus": 10.0, "health_bonus": -5},
	{"name": "Beetle Carapace", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "chest",
		"model": "carapace", "color": Color(0.24, 0.36, 0.20),
		"health_bonus": 42, "move_mod": -0.3, "jump_mod": -0.3},
]

const PANTS := [
	{"name": "Cloth Trousers", "rarity": "Common", "tier": 1, "edition": 92, "slot": "legs",
		"model": "trousers", "color": Color(0.34, 0.32, 0.50),
		"move_mod": 0.2, "stamina_bonus": 10.0},
	{"name": "Leather Leggings", "rarity": "Common", "tier": 1, "edition": 75, "slot": "legs",
		"model": "leather_legs", "color": Color(0.42, 0.28, 0.16),
		"health_bonus": 10},
	{"name": "Padded Leggings", "rarity": "Common", "tier": 1, "edition": 60, "slot": "legs",
		"model": "padded", "color": Color(0.50, 0.46, 0.40),
		"health_bonus": 12, "stamina_bonus": 8.0},
	{"name": "Iron Greaves", "rarity": "Uncommon", "tier": 2, "edition": 24, "slot": "legs",
		"model": "greaves", "color": IRON,
		"health_bonus": 20, "move_mod": -0.3, "jump_mod": -0.5},
	{"name": "Ranger Leggings", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "legs",
		"model": "wraps", "color": Color(0.24, 0.40, 0.26),
		"move_mod": 0.35, "jump_mod": 0.4, "stamina_bonus": 10.0},
	{"name": "Bone Legguards", "rarity": "Rare", "tier": 3, "edition": 6, "slot": "legs",
		"model": "bone_legs", "color": BONE,
		"health_bonus": 15, "move_mod": 0.1},
	{"name": "Windstep Trousers", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "legs",
		"model": "swift", "color": Color(0.70, 0.82, 0.92),
		"move_mod": 0.5, "jump_mod": 0.6, "stamina_bonus": 5.0, "health_bonus": -5},
	{"name": "Steel Legplates", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "legs",
		"model": "plate_legs", "color": STEEL,
		"health_bonus": 35, "move_mod": -0.5, "jump_mod": -0.7},
	{"name": "Fur Leggings", "rarity": "Uncommon", "tier": 2, "edition": 27, "slot": "legs",
		"model": "fur_legs", "color": Color(0.40, 0.28, 0.18),
		"health_bonus": 14, "stamina_bonus": 5.0, "move_mod": -0.05},
	{"name": "Chain Leggings", "rarity": "Uncommon", "tier": 2, "edition": 20, "slot": "legs",
		"model": "chain_legs", "color": Color(0.55, 0.57, 0.62),
		"health_bonus": 20, "move_mod": -0.2},
	{"name": "Traveler's Boots", "rarity": "Rare", "tier": 3, "edition": 9, "slot": "legs",
		"model": "boots_tall", "color": Color(0.36, 0.26, 0.16),
		"move_mod": 0.4, "jump_mod": 0.3, "stamina_bonus": 8.0},
	{"name": "Dragonscale Legs", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "legs",
		"model": "dragon_legs", "color": Color(0.24, 0.42, 0.28),
		"health_bonus": 28, "move_mod": -0.25, "jump_mod": -0.3},
	{"name": "Royal Greaves", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "legs",
		"model": "royal_legs", "color": Color(0.22, 0.32, 0.58),
		"health_bonus": 24, "stamina_bonus": 6.0, "move_mod": -0.3},
	{"name": "Steel Tassets", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "legs",
		"model": "tassets", "color": STEEL,
		"health_bonus": 30, "move_mod": -0.35, "jump_mod": -0.4},
	{"name": "Flame Legplates", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "legs",
		"model": "flame_legs", "color": Color(0.45, 0.16, 0.10),
		"health_bonus": 22, "stamina_bonus": 6.0, "move_mod": -0.25},
	{"name": "Frost Legplates", "rarity": "Epic", "tier": 4, "edition": 4, "slot": "legs",
		"model": "ice_legs", "color": Color(0.50, 0.66, 0.78),
		"health_bonus": 24, "move_mod": -0.25, "jump_mod": -0.25},
	{"name": "Radiant Greaves", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "legs",
		"model": "holy_legs", "color": Color(0.92, 0.90, 0.80),
		"health_bonus": 26, "regen_bonus": 6.0, "move_mod": -0.3},
	{"name": "Shadow Leggings", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "legs",
		"model": "shadow_legs", "color": Color(0.14, 0.10, 0.18),
		"move_mod": 0.35, "stamina_bonus": 12.0, "health_bonus": -8},
	{"name": "Bark Legs", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "legs",
		"model": "druid_legs", "color": Color(0.36, 0.26, 0.16),
		"health_bonus": 18, "stamina_bonus": 8.0, "move_mod": -0.1},
	{"name": "Crystal Legs", "rarity": "Epic", "tier": 4, "edition": 3, "slot": "legs",
		"model": "crystal_legs", "color": Color(0.40, 0.74, 0.82),
		"health_bonus": 22, "stamina_bonus": 10.0, "move_mod": -0.3},
	{"name": "Knight's Faulds", "rarity": "Uncommon", "tier": 2, "edition": 17, "slot": "legs",
		"model": "faulds", "color": Color(0.58, 0.60, 0.66),
		"health_bonus": 22, "move_mod": -0.25},
	{"name": "Indigo Hakama", "rarity": "Rare", "tier": 3, "edition": 8, "slot": "legs",
		"model": "hakama", "color": Color(0.22, 0.24, 0.46),
		"stamina_bonus": 14.0, "regen_bonus": 5.0, "move_mod": 0.15},
	{"name": "Linen Shorts", "rarity": "Uncommon", "tier": 2, "edition": 40, "slot": "legs",
		"model": "shorts", "color": Color(0.62, 0.56, 0.42),
		"move_mod": 0.3, "jump_mod": 0.25, "stamina_bonus": 6.0, "health_bonus": -3},
	{"name": "Spiked Greaves", "rarity": "Uncommon", "tier": 2, "edition": 15, "slot": "legs",
		"model": "spiked_legs", "color": Color(0.34, 0.36, 0.42),
		"health_bonus": 24, "move_mod": -0.2},
	{"name": "Scale Leggings", "rarity": "Uncommon", "tier": 2, "edition": 18, "slot": "legs",
		"model": "scale_legs", "color": Color(0.40, 0.48, 0.40),
		"health_bonus": 26, "move_mod": -0.25},
	{"name": "Winged Boots", "rarity": "Epic", "tier": 4, "edition": 2, "slot": "legs",
		"model": "winged_boots", "color": Color(0.70, 0.82, 0.92),
		"move_mod": 0.5, "jump_mod": 0.6, "stamina_bonus": 8.0, "health_bonus": -5},
]


## Every armor item in the catalog (helmets + chests + pants), as fresh copies so
## callers can mutate their own instances without touching the constants.
static func all_items() -> Array:
	var out: Array = []
	for group in [HELMETS, CHESTS, PANTS]:
		for item in group:
			out.append((item as Dictionary).duplicate(true))
	return out
